/**
 * Learner-facing copy for the student and demo routes.
 *
 * Keep infrastructure vocabulary out of this layer. Product concepts such as
 * equations, encounters, and mechanics stay visible when they help a learner
 * understand what they are making or playing.
 */
export const studentCopy = {
  navigation: {
    home: "Home",
    lessons: "My lessons",
    builder: "Make a lesson",
    progress: "Progress",
    play: "Play",
    profile: "Profile",
    logout: "Log out",
  },
  dashboard: {
    welcomeKicker: "WELCOME BACK",
    welcome: (name: string) => `Welcome back, ${name}`,
    welcomeBody: "Lessons from your teacher will show up here.",
    queueTitle: "Next up",
    queueEmptyTitle: "Nothing here yet",
    queueEmptyBody: "Lessons from your teacher will appear here.",
    queueEmptyAction: "Pick a game below while you wait.",
    gamesTitle: "Play a game",
    play: "Play",
    comingSoon: "Coming soon",
    gameDescriptions: {
      numberBonds: "Put numbers together to make a bigger number.",
      equations: "Find out when two sides are equal.",
      missingNumbers: "Find the number that makes the equation true.",
      earlyAlgebra: "Use letters for numbers you do not know yet.",
    },
  },
  songChoice: {
    title: "Pick a song",
    subtitle: "Choose a song, then decide how you want to play.",
    searchPlaceholder: "Find a song",
    searchLabel: "Find a song",
    unknownArtist: "Artist not listed",
    noSongsTitle: "No songs found",
    noSongsBody: "Try a different search.",
    back: "Back",
    continue: "Continue",
    preparing: "Getting ready…",
    preparingMessage: "Your song is getting ready. Try again in a moment.",
    chooseHowToStart: "How do you want to play?",
    readyToPlayBody: "This lesson is ready. Play it now, or make your own copy and change it first.",
    needsWorkBody: "You can make changes, but this lesson needs a few more pieces before it can play.",
    makeCopy: "Make your own copy",
    makeCopyBody: "Change a move or add an equation. The original stays safe.",
    playLesson: "Play this lesson",
    playLessonBody: "Play the ready-made lesson now. You can change it later.",
    chooseDifferentSong: "Choose a different song",
  },
  editor: {
    changeSong: "Song",
    changeSongLabel: "Choose a different song or activity",
    playLesson: "Play",
    playLessonLabel: "Play this lesson",
    saveLesson: "Save lesson",
    saveLessonLabel: "Save lesson changes",
    readyToPlay: "Ready to play!",
    readyCheck: "Ready check",
    ready: "Ready to play",
    thingsToFix: (count: number) => `${count} thing${count === 1 ? "" : "s"} to fix`,
    pickSongBeforePlay: "Pick a song before you play this lesson.",
    finishLoadingBeforeSave: "Your lesson is still loading. Try again in a moment.",
    gameFilesPreparing: "Your lesson is still getting ready.",
    noChanges: "There are no new changes to save. This lesson is ready to play.",
    draftSaved: "Your changes are saved on this device.",
    draftRecoveryFailed: "Your lesson is still open, but this device could not save a backup.",
    lessonLoaded: "Your lesson is ready.",
    lessonLoadFailed: "We could not load this lesson. Your current work is still here.",
    lessonSaveFailed: "We could not save these changes. Your current work is still here.",
    changesSaved: "Your lesson changes are saved.",
    newerChangesRemain: "Your saved lesson is updated. Newer changes are still open here.",
    savedSnapshot: (song: string, activity: string) => `${song} is saved for ${activity}.`,
    advancedTools: "More tools",
    advancedToolsTitle: "Open more lesson tools?",
    advancedToolsBody: "These tools let you place and move every part of the lesson. Your changes stay safe while you work.",
    openAdvancedTools: "Open more tools",
    keepEditing: "Keep editing",
    saveAndLeave: "Save and leave",
    leaveWithoutSaving: "Leave without saving",
    unsavedTitle: "Save your changes?",
    unsavedBody: "You have changes that are not saved yet. Save them before you leave?",
    tutorialSkip: "Skip tips",
    tutorialEquation: "Click the number and symbol buttons to build an equation.",
    equationPreview: "Your equation",
    saveEquation: "Save this equation",
    useEquationForGroup: (group: string) => `Use this equation for every move in ${group}`,
    emptyEquation: "Drag a number or symbol here to start.",
    moveGroup: (number: number) => `Encounter ${number}`,
    editingMoveGroup: (number: number) => `Editing encounter ${number} · choose a move or change its equation`,
    starterLabel: "Starting lesson",
    starterBody: "This lesson is ready to play. Keep it, change one encounter, or add an equation.",
    changeFirstMove: "Change first encounter",
    addEquation: "Add an equation",
    keepIt: "Keep it",
    moveRemoved: (kind: string) => `${kind} removed.`,
    noMoveToRemove: (kind: string) => `There is no ${kind.toLowerCase()} to remove yet.`,
    moveAdded: (kind: string, time: string) => `${kind} added at ${time}.`,
    moveDrafted: (kind: string, time: string, nextAction: string) => `${kind} started at ${time}. ${nextAction}`,
    chooseEventFirst: "Pick an encounter on the timeline first.",
    equationNeedsBothSides: "Add something on both sides of the = sign to finish the equation.",
    chooseSong: "Pick a song before you continue.",
  },
  mechanics: {
    hit: "Hit",
    spin: "Spin",
    drag: "Drag",
    makeHit: "Make a Hit",
    makeSpin: "Make a Spin",
    makeDrag: "Make a Drag",
    pickHitTarget: "Pick what to hit",
    pickSpinTarget: "Pick what to spin",
    pickDragTarget: "Pick what to drag",
    chooseButtons: "Choose the buttons to press",
    operatorHint: "You cannot choose + or =. Pick a number or variable.",
    chooseEquation: "Choose an equation to get started.",
    chooseEarlierHit: "Start from an earlier Hit",
    chooseEarlierHitOption: "Choose a Hit",
    chooseEarlierHitLabel: "Choose the earlier Hit to start from",
    connectEarlierHit: "Connect the earlier Hit to this target.",
    spinCue: "Spin this token while the move is active.",
    startTime: "Starts at",
    endTime: "Ends at",
  },
  game: {
    handoffError: "We could not verify this lesson. Go back and start it again.",
    calibrationSaveFailed: "Your setup is finished, but we could not save it. Try again before you leave.",
    resultSyncFailed: "Your result is waiting to be saved. Keep this tab open and try again.",
    prepareErrorTitle: "We could not get this lesson ready",
    chooseSongTitle: "Pick a song to play",
    preparingTitle: "Getting your game ready…",
    chooseSongBody: "Pick a song first, then come back here to play.",
    preparingBody: "Your game is getting ready.",
    chooseAnotherSong: "Choose another song",
    chooseSong: "Pick a song",
    calibrationRequired: "Finish the quick setup in the game before you play.",
    savingResult: "Saving your result…",
    syncAgain: "Save result again",
    waitingToSave: "Your result is still waiting to be saved.",
    lessonComplete: (events: number, attempts: number) => `Lesson complete: ${events} moves finished in ${attempts} tries.`,
    returnToSongs: "Choose another song when you are ready.",
  },
} as const;

/** Keep technical launch failures out of learner-facing surfaces. */
export function getLearnerFacingError(error: unknown, fallback: string): string {
  const raw = error instanceof Error ? error.message.trim() : String(error ?? "").trim();
  if (!raw) return fallback;

  if (/operator|gameplay target/i.test(raw)) return studentCopy.mechanics.operatorHint;
  if (/equation/i.test(raw) && /assign|complete|missing|required/i.test(raw)) {
    return studentCopy.mechanics.chooseEquation;
  }
  if (/workspace|recovery copy|backup|sync/i.test(raw)) return studentCopy.editor.draftRecoveryFailed;
  if (/load|prepare|package|chart|sidecar|lesson files/i.test(raw)) return studentCopy.editor.lessonLoadFailed;
  if (/save|publish|revision|identity|verified/i.test(raw)) return studentCopy.editor.lessonSaveFailed;
  return fallback;
}
